---
format: 
  pdf:
    mainfont: Brill
    header-includes: |
       \usepackage{caption}
       \captionsetup[subfigure]{labelformat=empty}
editor: source
---

\LARGE

Уважаемые соседи!

\vfill

До **24 октября 2024** года идет голосование по вопросам, вынесенным управляющей компанией. Представители УК на прошлом собрании (09.09.2024) подтвердили, что регламент в данный момент изменению не подлежит и голосование невозможно отменить, активная группа собственников предлагает несмотря на звучащую категоричность формулировки обдуманно проголосовать ПРОТИВ всех пунктов. Это позволит коллективно доработать каждый пункт повестки с учетом пожелания жильцов. Активная группа собственников внимательно рассмотрел вопросы повестки, и сформулировал свое мнение по каждому из них.  Со всеми документами можно ознакомиться ниже в формате `.pdf`:

\vfill

```{r}
#| echo: false
#| fig-align: left
#| layout-ncol: 2
#| fig-subcap: 
#|  - "\\LARGE Решение актива"
#|  - "\\LARGE Бюллетень УК"

qrcode::qr_code("https://raw.githubusercontent.com/agricolamz/2024.09.09_info_donskoy/refs/heads/main/2024.09.16_recommendation.PDF", ecl = "L") |> plot()

qrcode::qr_code("https://raw.githubusercontent.com/agricolamz/2024.09.09_info_donskoy/refs/heads/main/2024.09.09_ballot_paper.PDF", ecl = "L") |> plot()
```

С уважением, 

А. Назаров (кв. 9, 139), М. Ксинопуло (кв. 10), А. Рахтеенко (кв. 58), И. Марич (кв. 131), М. Денисюк (кв. 135), А. Власов (кв. 141), Н. Ракитянская (кв. 142)
